### ISSUE TITLE
pip2 will stop working in january

### ISSUE THREAD

**Issue by sosiouxme** [openshift/art-ci-toolkit#9]
https://github.com/openshift/art-ci-toolkit/blob/1a7ecf46d042b5185bfa447ab13a48bd6fce68dd/Dockerfile#L20

@thiagoalessio couldn't this safely move to pip3?
not sure what to do about koji though

**Comment by thiagoalessio** [comment]
I got rid of Python 2 altogether, `koji` and the rest installed just fine.
(had a small issue with `pygit2`, but installing it through `yum` seems to work)

here is the latest build: https://quay.io/repository/openshift-art/art-ci-toolkit/build/f6dce2dd-2a96-43e0-aa2d-7c1788723693

**Comment by sosiouxme** [comment]
Thanks!
